<?php

namespace App\Services\Payment;

/**
 * NisMath — Pure Math Trait
 * ═════════════════════════
 * All calculation methods are pure functions: same inputs → same outputs,
 * no side effects, no database access. This makes them trivially unit-testable.
 *
 * Consumed by PaymentService. Can also be used directly in Livewire components
 * or Blade views for live previews (e.g. the Add Modal angsuran calculator).
 */
trait NisMath
{
    // ── Constants ──────────────────────────────────────────────────────────

    /** NIS receives exactly 30% of every actual monthly payment */
    protected const NIS_RATE = 0.30;

    /** Land price per m² — permanent, defines the kavling ceiling */
    protected const LAND_PRICE_PER_SQM = 4_000_000;

    // ══════════════════════════════════════════════════════════════════════
    // KAVLING (LAND CEILING)
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Kavling value = LT (m²) × Rp 4,000,000
     *
     * This is the PERMANENT CEILING for the cumulative NIS land share on a unit.
     * Once cumulative capped_nis_share reaches this value, the land account is done.
     *
     * Example: LT = 75 m² → Kavling = Rp 300,000,000
     */
    public function kavlingValue(int $luasTanah): int
    {
        return $luasTanah * self::LAND_PRICE_PER_SQM;
    }

    /**
     * How much kavling headroom remains before the ceiling is hit.
     * Returns 0 once the unit is land-cleared (never negative).
     *
     * @param int $kavlingValue     The unit's permanent ceiling (from kavlingValue())
     * @param int $previousCumNis   Sum of all capped_nis_share BEFORE this payment
     */
    public function remainingKavlingHeadroom(int $kavlingValue, int $previousCumNis): int
    {
        return max(0, $kavlingValue - $previousCumNis);
    }

    /**
     * Whether the unit's land account has been fully settled.
     */
    public function isLandCleared(int $kavlingValue, int $cumulativeNis): bool
    {
        return $cumulativeNis >= $kavlingValue;
    }

    // ══════════════════════════════════════════════════════════════════════
    // NIS SHARE CALCULATIONS
    // ══════════════════════════════════════════════════════════════════════

    /**
     * The NIS share that SHOULD have been received if the buyer paid exactly on target.
     * supposed_nis_share = target_amount × 0.30
     */
    public function supposedNisShare(int $targetAmount): int
    {
        return (int) round($targetAmount * self::NIS_RATE);
    }

    /**
     * The NIS share that WAS actually generated by the real payment.
     * actual_nis_share = actual_amount × 0.30
     *
     * This may differ from supposed_nis_share when the buyer under/overpays.
     */
    public function actualNisShare(int $actualAmount): int
    {
        return (int) round($actualAmount * self::NIS_RATE);
    }

    /**
     * The effective (capped) NIS share after applying the kavling ceiling.
     *
     * Rule: Once the cumulative NIS share hits the kavling cap, stop routing
     *       money to the land account. The capped share is the lesser of:
     *         (a) the raw actual_nis_share, or
     *         (b) whatever headroom is left before the ceiling
     *
     * @param int $actualNisShare       = actualNisShare(actual_amount)
     * @param int $kavlingHeadroom      = remainingKavlingHeadroom(...) BEFORE this payment
     */
    public function cappedNisShare(int $actualNisShare, int $kavlingHeadroom): int
    {
        return min($actualNisShare, $kavlingHeadroom);
    }

    // ══════════════════════════════════════════════════════════════════════
    // VARIANCE & PAYMENT STATUS
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Variance = actual_amount − target_amount
     *   > 0 → overpay / accelerated
     *   = 0 → correct
     *   < 0 → underpay
     */
    public function variance(int $actualAmount, int $targetAmount): int
    {
        return $actualAmount - $targetAmount;
    }

    /**
     * Classify a payment into one of three statuses based on variance.
     *
     * @return string 'correct' | 'underpay' | 'overpay'
     */
    public function paymentStatus(int $variance): string
    {
        return match(true) {
            $variance > 0 => 'overpay',
            $variance < 0 => 'underpay',
            default       => 'correct',
        };
    }

    /**
     * Human-readable variance note for the audit ledger display.
     *   underpay → "(Short: -Rp 10,000,000)"
     *   overpay  → "(Excess: +Rp 5,000,000)"
     *   correct  → ""
     */
    public function varianceNote(int $variance): string
    {
        return match(true) {
            $variance < 0 => sprintf('(Short: -Rp %s)',   number_format(abs($variance), 0, ',', '.')),
            $variance > 0 => sprintf('(Excess: +Rp %s)',  number_format($variance,      0, ',', '.')),
            default       => '',
        };
    }

    /**
     * Status label with emoji for display in the installment ledger.
     *   correct  → "✅ Correct"
     *   underpay → "❌ Underpay"
     *   overpay  → "⚠️ Overpay / Accelerated"
     */
    public function statusLabel(string $paymentStatus): string
    {
        return match($paymentStatus) {
            'correct'  => '✅ Correct',
            'underpay' => '❌ Underpay',
            'overpay'  => '⚠️ Overpay / Accelerated',
            default    => '— Unknown',
        };
    }

    // ══════════════════════════════════════════════════════════════════════
    // INSTALLMENT CALCULATION
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Monthly installment = (harga_penjualan − down_payment) ÷ max_installments
     * Rounded to nearest whole Rupiah.
     */
    public function angsuranPerBulan(int $harga, int $dp, int $maxInstallments): int
    {
        if ($maxInstallments <= 0) {
            return 0;
        }
        return (int) round(($harga - $dp) / $maxInstallments);
    }

    /**
     * The NIS share of a perfectly on-target monthly payment.
     * penerimaan_per_bulan = angsuran_per_bulan × 0.30
     */
    public function penerimaanPerBulan(int $angsuranPerBulan): int
    {
        return (int) round($angsuranPerBulan * self::NIS_RATE);
    }

    // ══════════════════════════════════════════════════════════════════════
    // FORMATTING HELPERS
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Format a Rupiah integer for display.
     * e.g. 300000000 → "Rp 300.000.000"
     */
    public function formatRp(int $amount): string
    {
        return 'Rp ' . number_format($amount, 0, ',', '.');
    }

    /**
     * Format a payment date in Indonesian locale.
     * e.g. Carbon date for 2024-03-01 → "1 Maret 2024"
     */
    public function formatIndonesianDate(\Carbon\Carbon $date): string
    {
        $months = [
            1 => 'Januari',   2 => 'Februari', 3 => 'Maret',
            4 => 'April',     5 => 'Mei',       6 => 'Juni',
            7 => 'Juli',      8 => 'Agustus',   9 => 'September',
            10 => 'Oktober', 11 => 'November', 12 => 'Desember',
        ];

        return sprintf('%d %s %d', $date->day, $months[$date->month], $date->year);
    }
}
